{{- if $.Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{- $.Values.externalSecret.name | default (include "fullname" $) -}}-external-secret"
  {{- include "annotations" $ | indent 2 }}
  {{- include "labels" $ | indent 2 }}
spec:
  refreshInterval: "{{- $.Values.externalSecret.refreshInterval | default "1h0m0s" -}}"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: "{{- $.Values.externalSecret.name | default (include "fullname" $) -}}-external-secret"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "/k8s/{{- $.Values.externalSecret.name | default (include "fullname" $) -}}"
{{- end -}}
